version: '3.8'

services:
  ollama-mistral:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-mistral
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0 # Good for external access
      # You might also consider setting OLLAMA_MODELS=/root/.ollama/models
      # if you want to be super explicit about where models are stored within the volume.
      # However, /root/.ollama is the default parent directory for models anyway.
    healthcheck:
      # Test if /api/tags returns a list containing 'mistral'
      test: ["CMD", "sh", "-c", "curl -f http://localhost:11434/api/tags | grep -q '\"name\": \"mistral\"'"]
      interval: 30s
      timeout: 10s
      retries: 10 # Increase retries, as it will fail until mistral is pulled
      start_period: 60s # Give it some initial time, then it will keep retrying
      # You might need to increase start_period significantly if the pull is very long,
      # but with the grep check, it will just keep trying every `interval`.

volumes:
  ollama_data:
    driver: local